# Generated by Django 5.1 on 2025-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'مفعل'), ('inactive', 'معطل')], default='active', max_length=10),
        ),
    ]
