# Generated by Django 5.1 on 2025-03-22 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gv_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('governates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generals.governates')),
            ],
        ),
        migrations.CreateModel(
            name='AreaSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^\\d{2}-\\d{2}$')])),
                ('end_date', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^\\d{2}-\\d{2}$')])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generals.areas')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generals.seasons')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('area', 'season'), name='unique_area_season')],
            },
        ),
    ]
