# Generated by Django 5.1 on 2025-03-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_rename_inventory_state_inventory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinventory',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'كيلو'), ('box', 'سلة'), ('bundle', 'ربطة'), ('cup', 'قدح'), ('bag', 'كيس')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'كيلو'), ('box', 'سلة'), ('bundle', 'ربطة'), ('cup', 'قدح'), ('bag', 'كيس')], max_length=100, null=True),
        ),
    ]
