# Generated by Django 5.1 on 2025-03-15 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generals.areas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('farmer', 'مزارع'), ('merchant', 'تاجر'), ('customer', 'عميل')], max_length=100, null=True),
        ),
    ]
