# Generated by Django 5.1 on 2025-03-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_profile_account'),
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_account', to='usermanage.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
