# Generated by Django 5.1 on 2025-03-22 17:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('fruite', 'الفواكه'), ('vegetable', 'الخضار'), ('grain', 'الحبوب'), ('herbs', 'الاعشاب'), ('ornamental', 'الزينة')], max_length=255)),
                ('category_image', models.ImageField(upload_to='photo/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255, verbose_name='اسم النبات')),
                ('water_requirement', models.PositiveIntegerField(verbose_name='احتياج الماء')),
                ('fertilizer_requirement', models.PositiveIntegerField(verbose_name='احتياج السماد')),
                ('harvest', models.PositiveIntegerField(verbose_name='مدة الحصاد (يوم)')),
                ('validity', models.PositiveIntegerField(default=0, verbose_name='صلاحية المنتج (يوم)')),
                ('informations', models.TextField(verbose_name='معلومات إضافية')),
                ('image', models.ImageField(upload_to='plants/main/', verbose_name='الصورة الرئيسية')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='plants/extra/', verbose_name='صورة إضافية 1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='plants/extra/', verbose_name='صورة إضافية 2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='plants/extra/', verbose_name='صورة إضافية 3')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='plantations.categories', verbose_name='الصنف')),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255)),
                ('planting_date', models.DateField(default=django.utils.timezone.now)),
                ('next_watering_date', models.DateField(blank=True, null=True)),
                ('next_fertilization_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('growing', 'ينمو'), ('harvested', 'تم الحصاد'), ('failed', 'تالف')], default='growing', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantations.plants')),
            ],
        ),
    ]
