# Generated by Django 5.1 on 2025-04-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
