# Generated by Django 5.1 on 2025-03-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(choices=[('fruite', 'الفواكه'), ('vegetable', 'الخضار'), ('grain', 'الحبوب'), ('herbs', 'الاعشاب'), ('ornamental', 'الزينة')], max_length=255),
        ),
    ]
