# Generated by Django 5.1 on 2025-03-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='title',
        ),
    ]
